### ISSUE TITLE
Wildcard patterns and/or partial assembly names in the include/exclude configuration

### ISSUE THREAD

**Issue by brutaldev** [Fody/LoadAssembliesOnStartup#162]
## Summary
Allow wildcards or partial assembly names in the include/exclude configuration. `SystemAssemblyPrefixes` already does this for partial matching but the include and exclude configuration expects exact names preventing once off configuration to load future assemblies with the same names/pattern (like plugins).

## API Changes
Modify line [164](https://github.com/Fody/LoadAssembliesOnStartup/blob/a5105272d84e6fc474fe0066ca9bd3f8bef64d23/src/LoadAssembliesOnStartup.Fody/Weaving/ReferenceSelector.cs#L164) and line [175](https://github.com/Fody/LoadAssembliesOnStartup/blob/a5105272d84e6fc474fe0066ca9bd3f8bef64d23/src/LoadAssembliesOnStartup.Fody/Weaving/ReferenceSelector.cs#L175) in `ReferenceSelector.cs` to match a partial pattern like `SystemAssemblyPrefixes` on line [191](https://github.com/Fody/LoadAssembliesOnStartup/blob/a5105272d84e6fc474fe0066ca9bd3f8bef64d23/src/LoadAssembliesOnStartup.Fody/Weaving/ReferenceSelector.cs#L191)

## Intended Use Case
Loading plugin types up-front. Typically plugin assemblies will follow a pattern like `Company.Plugin.*" so to avoid having to know at compile time which of these to manually add that extra step could be avoided by using a pattern so that the types are just loaded no matter how many get referenced over time.

**Comment by GeertvanHorrik** [comment]
I see a few things that need to be taken care of to prevent any side effects:

1. We need to explicitly enable this (by pre/suf fixing with a *)
2. We need to change it from Contains to StartsWith (only * at the front), EndsWith (only * at the end) or Contains(* front and back)

Interested in doing a PR for this?

**Comment by brutaldev** [comment]
@GeertvanHorrik Guess I could, busy with a critical deadline today, I'll handle this tonight.

**Comment by brutaldev** [comment]
@GeertvanHorrik Made the changes quickly but couldn't even load the solution to compile or test. Minor changes to enable wild cards while still maintaining backward compatibility with exact matches so you do not need to opt-in (number 1) and it's more flexible allowing any wild card pattern so no need for StartsWith and EndsWith calls. You can ignore the PR if you want because I didn't comply with all the PR requirements but I need to get back to another project, at least this is an example of the solution I would like to have in place.

**Comment by brutaldev** [comment]
Hi, please could you include this change or apply similar capabilities to allow to wild card type matching.

**Comment by GeertvanHorrik** [comment]
Yes, whenever we have more time, we will look into this.

**Comment by GeertvanHorrik** [comment]
Working on some unit tests now.

**Comment by GeertvanHorrik** [comment]
Build - 4.5.0-alpha.203 should be available in about 20 minutes on NuGet. Please let me know if this works for you, then I'll release a stable version.

**Comment by brutaldev** [comment]
Updated and changed to wild card matches and it works well.

**Comment by GeertvanHorrik** [comment]
Thanks, releasing stable version now.

**Comment by brutaldev** [comment]
Thanks, updated to the official release. Appreciate the help.
