### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [Fody/LoadAssembliesOnStartup#3]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency range for Fody to be at least 2.0

 Please ping me if u need help

**Comment by GeertvanHorrik** [comment]
@SimonCropp for my understanding, I need to get rid of the actual Mono.Cecil reference and replace it with the FodyCecil one?

**Comment by GeertvanHorrik** [comment]
Done, Build - 1.8.0-unstable.3 is now available on NuGet. Will release as stable once the other issue has been resolved as well.
