### ISSUE TITLE
FeatureRequest: do NOT load on startup (but generate the Load method)

### ISSUE THREAD

**Issue by wexman** [Fody/LoadAssembliesOnStartup#96]
### Feature description

I would like to be able to NOT have the referenced assemblies load on startup, but at a certain point in the flow of my app (when some intializations have been made). This would require that the LoadTypesOnStartup method be generated as it is today (so I can call it whenever I want), but just not invoked on startup.
Seems to me like that should be easy to achieve (but I might be wrong here of course ;-)

**Comment by GeertvanHorrik** [comment]
This is indeed fairly easy to achieve, I think we can follow a similar path as Costura.

**Comment by wexman** [comment]
Indeed - so easy that I'm just creating a pull request ;-)

**Comment by GeertvanHorrik** [comment]
You're too fast, I wanted to check where to put this, but you are already done :-)
